config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  root to: 'pages#show_all'

  get 'pages/show_all'
  get 'pages/new'
  get 'pages/user/:username', to: 'pages#user'
  

  resources :statuses
  resources :questions
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
    belongs_to :status
    belongs_to :user
    
    validates :question, presence: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]
  before_action :set_statuses
  before_action :authenticate_user, only: [:index, :show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all.order('status_id ASC')
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    
    question_params2= question_params
    
    # ユーザーがログインしていたら、paramsにIDを追加する
    if user_signed_in? then 
      question_params2["user_id"] = current_user.id
    end
    
    @question = Question.new(question_params2)
    path = Rails.application.routes.recognize_path(request.referer)
    
    respond_to do |format|
      
      if @question.save
        if(path[:controller]=="pages") then
                  format.html { redirect_to pages_show_all_path, notice: '要望を受けつけました。回答をお待ちください。' }
        end
          format.html { redirect_to @question, notice: 'Question was successfully created.' }
          format.json { render :show, status: :created, location: @question }
      else
        if(path[:controller]=="pages") then
          p @question.errors
          format.html { redirect_to pages_new_path, errors: @question.errors}
          
        end
          format.html { render :new }
          format.json { render json: @question.errors, status: :unprocessable_entity }
        
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        
        format.html { redirect_to questions_path, notice: 'Question was successfully updated.' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: 'Question was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:question, :answer, :status_id, :user_id)
    end
    
    def set_statuses
      @statuses = Status.all
      @users = User.all
    end
    
    def authenticate_user
      if !user_signed_in? then
        redirect_to new_user_session_path , notice: 'ログインしてください。'
      end
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>
      <ul>
      <% question.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <div class="field">
      <%= form.label 'ご意見やご要望' %>
      <%= form.text_area :question, id: :question_question, class:'form-control',:placeholder => "こちらに入力してください。" %>
    </div>
    <div class="field">
      <%= form.label '回答' %>
      <%= form.text_area :answer, id: :question_answer, class:'form-control',:placeholder => "回答を入力してください。" %>
    </div>
    <div class="field">
      <%= form.select :status_id, @statuses.map{|t| [t.name,t.id]} %>
    </div>
  </div>
  <div class="actions">
    <%= form.submit class:'btn btn-primary btn-lg',value:'送信する',data: { disable_with: "送信中..." } %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<div class="container text-center new_question_block">
    <div class="container text-center">
        <h3 class="jumbotron-heading">ご意見NO.<%= params[:id] %></h3>
    </div>
  
  <div class="row d-flex justify-content-center">
    <div class="col-xs-6 col-sm-4 col-md-6">
      <%= render 'form', question: @question %>
      <div class="d-flex justify-content-between">
       <%= link_to '戻る', questions_path %>
        <p class="btn btn-danger btn_new_question">
            <%= link_to '削除する', question_url(@question.id), method: :delete, data: { confirm: 'Are you sure?' } %>
        </p>
      </div>
    </div>
  </div>

</div>

      

app/views/questions/index.html.erb
<div class="container new_question_block back_office_show_all bg-light">
  <div class="container text-center">
    <h3 class="jumbotron-heading">ご意見一覧 管理画面</h3>
        <ul class="question_status_list">
          <li class="btn btn-light my-2" data-group="all">全て</li>
          <li class="btn btn-danger my-2" data-group="new_issue">新規</li>
          <li class="btn btn-primary my-2" data-group="done">改善しました</li>
          <li class="btn btn-success my-2" data-group="pending">検討中</li>
          <li class="btn btn-secondary my-2" data-group="reject">対応なし</li>
        </ul>
  </div>

  <div class="row d-flex justify-content-center issues_all">
      <% @questions.each do |question| %>
        <div class="col-md-12 box-shadow issue card grid-item" data-group="<%= question.status.eng_name %>">
          <p class="back_qa_status bg-<%= question.status.eng_name %>"><%= question.status.name %></p>
          <div class="row d-flex justify-content-center">
            <div class="col-md-5 card-body">
              <p class="q_or_a">ご意見 NO. <%= question.id %></p>
              <p class="card-text"><%= question.question %></p>
            </div>
            <div class="col-md-5 card-body">
              <p class="q_or_a">回答</p>
              <p class="card-text"><% if question.answer %><%= question.answer %><% end %></p>
            </div>
            <div class="col-md-2 card-body">
              <% if question.answer %>
                <div class="text-center">
                  <p class="btn btn-primary btn_new_question"><%= link_to '編集する', edit_question_path(question) %></p>
                </div>
              <% else %>
                <div class="text-center">
                  <p class="btn btn-danger btn_new_question btn-lg"><%= link_to '回答する', edit_question_path(question) %></p>
                </div>
              <% end %>
            </div>
          </div>
          <div class="row d-flex justify-content-center">
            <div class="col-md-12 card-body">
              <small class="text-muted">作成日 : <%= question.created_at.strftime('%Y/%m/%d') %></small>&nbsp;
              <small class="text-muted">更新日 : <%= question.updated_at.strftime('%Y/%m/%d') %></small>&nbsp;
              <small class="text-muted">投稿者 : <%= question.user.try(:username) %></small>
            </div>
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @question.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @question.answer %>
</p>

<p>
  <strong>Status:</strong>
  <%= @question.status.try(:name) %>
</p>

<%= link_to 'Edit', edit_question_path(@question) %> |
<%= link_to 'Back', questions_path %>